dist: trusty
sudo: false

language: node_js
node_js:
  - "4"

addons:
  apt:
    packages:
      - google-chrome-stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
  - npm install

services:
  - mongodb

script:
  - node server.js &
  - npm test
